import pandas as pd
import numpy as np
import UnityEngine
df = pd.read_csv("01-01-2016-TO-01-01-2017-BRITANNIA-ALL-N.csv")
maincamera = UnityEngine.GameObject.Find("Main Camera")
slider_behaviour = maincamera.GetComponent("sliderbehaviour")
slider_behaviour.BRITopen(df["Open Price  "].to_list())
slider_behaviour.BRITclose(df["Close Price  "].to_list())
slider_behaviour.BRIThigh(df["High Price  "].to_list())
slider_behaviour.BRITlow(df["Low Price  "].to_list())
df = pd.read_csv("01-01-2016-TO-01-01-2017-HCLTECH-ALL-N.csv")
slider_behaviour.HCLopen(df["Open Price  "].to_list())
slider_behaviour.HCLclose(df["Close Price  "].to_list())
slider_behaviour.HCLhigh(df["High Price  "].to_list())
slider_behaviour.HCLlow(df["Low Price  "].to_list())
df = pd.read_csv("01-01-2016-TO-01-01-2017-TATASTEEL-ALL-N.csv")
slider_behaviour.TSopen(df["Open Price  "].to_list())
slider_behaviour.TSclose(df["Close Price  "].to_list())
slider_behaviour.TShigh(df["High Price  "].to_list())
slider_behaviour.TSlow(df["Low Price  "].to_list())
df = pd.read_csv("01-01-2016-TO-01-01-2017-TCS-ALL-N.csv")
slider_behaviour.TCSopen(df["Open Price  "].to_list())
slider_behaviour.TCSclose(df["Close Price  "].to_list())
slider_behaviour.TCShigh(df["High Price  "].to_list())
slider_behaviour.TCSlow(df["Low Price  "].to_list())
df = pd.read_csv("01-01-2016-TO-01-01-2017-WIPRO-ALL-N.csv")
slider_behaviour.WIPROopen(df["Open Price  "].to_list())
slider_behaviour.WIPROclose(df["Close Price  "].to_list())
slider_behaviour.WIPROhigh(df["High Price  "].to_list())
slider_behaviour.WIPROlow(df["Low Price  "].to_list())
